# Generated by Django 4.1 on 2022-11-21 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techpost',
            name='image_post',
            field=models.ImageField(upload_to='images'),
        ),
    ]
