# Generated by Django 4.1 on 2022-11-23 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_techpost_authors_text_commenttechpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='commenttechpost',
            name='id_techpost',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='commenttechpost',
            name='posts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.techpost'),
        ),
    ]
